import React, { useState, useEffect } from 'react';
import { Card, CardContent, Typography } from '@mui/material';


// Usage:
// <TypewriterText text={yourText} typingSpeed={50} />
const TypewriterText = ({ text, typingSpeed = 30, ...args }) => {
  const [displayedText, setDisplayedText] = useState('');
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isComplete, setIsComplete] = useState(false);

  useEffect(() => {
    // Reset state when text changes
    setDisplayedText('');
    setCurrentIndex(0);
    setIsComplete(false);
  }, [text]);

  useEffect(() => {
    if (!text) return;

    const contentToType = text.split("</think>")[1] || '';

    if (currentIndex < contentToType.length) {
      const timer = setTimeout(() => {
        setDisplayedText(prev => prev + contentToType[currentIndex]);
        setCurrentIndex(prevIndex => prevIndex + 1);
      }, typingSpeed);

      return () => clearTimeout(timer);
    } else {
      setIsComplete(true);
    }
  }, [text, currentIndex, typingSpeed]);

  return (
    <Card {...args} sx={{ width: '100%', minWidth: 'fit-content' }}>
      <CardContent>
        <Typography variant="h6" component="div">
          {displayedText}
        </Typography>
        <Typography
          variant="body1"
          sx={{
            color: 'text.secondary',
            mt: 1.5,
            opacity: isComplete ? 1 : 0,
            transition: 'opacity 0.5s ease-in-out'
          }}
        >
          {text ? "Generated by deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B" : ""}
        </Typography>
      </CardContent>
    </Card>
  );
};


export default TypewriterText;